### ISSUE TITLE
OPTIONS to get all searchable/filterable fields? 

### ISSUE THREAD

**Issue by nic-planet** [Element84/sat-tasking-sprint#14]
Different providers and different platforms even for a single provider will provide different fields to filter by.
An `OPTIONS` method to the same endpoint we'd use for getting opportunities could be used to figure out which fields are filterable before the actual call is made.

**Comment by jsignell** [comment]
This is similar to the `/queryable` endpoint on the STAC API: 

example: https://earth-search.aws.element84.com/v1/collections/landsat-c2-l2/queryables

**Comment by jsignell** [comment]
I think this idea has been overridden with the idea of the `/products` API. So I am closing this in favor of #67.
